Inital translations
cherta/js.uy pull request #12
Opened 2017-04-16 18:21 UTC by cherta

I tried hard not to add literal translations but to communicate the idea, maybe now the English version is a bit out of sync since the concept of the site has shifted since I first wrote the english pages. We may need to revisit the english pages as well.

The work is pretty straightforward, hugo enables translations by prefixing the language name to the file extensions. For example `contents/index.md` can be translated to spanish by creating a new file named `contents/index.es.md`.

There is still somre repeated code on the index page since it's not only content but some styles and the newsletter form, I think for now this works but if we find ourselves changing a lot the index page then we should move these resources to a more generic place.

2017-04-17 14:11 UTC, pepesenaris commented on content/_about.es.md
> +Creamos `☀️.js.uy` para promover las actividades y los intergantes de la comunidad JS en Uruguay y para hacer crecer la misma.
integrantes

2017-04-17 14:13 UTC, pepesenaris commented on content/_about.es.md
> +* Ayudar a las personas a marketearse mejor
"a darse a conocer" quizas? en lugar de marketearse

2017-04-17 14:14 UTC, pepesenaris commented on content/_about.es.md
> +* Poner a Uruguay en el mapa de la comundad JS global
comunidad

2017-04-17 14:41 UTC, san650 commented on content/_about.es.md
> +Creamos `☀️.js.uy` para promover las actividades y los intergantes de la comunidad JS en Uruguay y para hacer crecer la misma.
Cambiaría un poquito la redacción `promover las actividades y __potenciar__ a los integrantes`

2017-04-17 16:15 UTC, xymbol reviewed
Está muy bien, van algunos comentarios del uso del castellano y una leída rápida a la distancia.

2017-04-17 16:15 UTC, xymbol commented on config.toml
> +  name = "Sobre nosotros"
Usaría "acerca de".

2017-04-17 16:15 UTC, xymbol commented on config.toml
> +  name = "Cómo reclamo un dominio js.uy?"
Agregaría el signo de interrogación `¿` y usaría "agrego".

2017-04-17 16:15 UTC, xymbol commented on config.toml
> +  name = "Cómo reclamo un dominio js.uy?"
Usaría consigo o solicito... En castellano, reclamar es otra cosa. :-)

2017-04-17 16:15 UTC, xymbol commented on content/_about.es.md
> +En Uruguay existen muchas personas trabajando con JS al primer nivel pero a veces fallamos en comunicarle al resto del mundo lo que estamos haciendo. La mayoría de los desarrolladores fallamos en con
Repite fallamos, no es pa' tanto. Usaría omitimos o desaprovechamos la oportunidad.

2017-04-17 16:15 UTC, xymbol commented on content/_about.es.md
> +Creamos `☀️.js.uy` para promover las actividades y potenciar a los integrantes de la comunidad JS en Uruguay en pos de hacer crecer la misma.
Provover las actividades de la comunidad y potenciar a los integrantes.

2017-04-17 16:15 UTC, xymbol commented on content/_about.es.md
> +Creemos que ayudando a la difusión a nuestras actividades vamos a tener un impacto positivo en las carreras de las personas. Ayudándolos a tener más notoriedad en la comunidad internacional y que est
Repite actividades, usaría visibilidad en vez de notoriedad. Le bajaría un poco el tono casi nacionalista. Usaría ingresos en vez de sueldos (que implica relación de dependencia). Usaría "poder trabajar en o con" en vez de "elegir".

2017-04-17 16:15 UTC, xymbol commented on content/_about.es.md
> +* Ayudar a las personas a darse conocer mejor
Ayudar a los miembros a darse **a** conocer.

2017-04-17 16:15 UTC, xymbol commented on content/_about.es.md
> +* Mejorar la colaboración dentro de la comunidad uruguaya de desarrolladores
Usaría oriental o local, se puede decir lo mismo sin que choque.

2017-04-17 16:15 UTC, xymbol commented on content/_claim_domain.es.md
> +## Cómo reclamo un dominio js.uy?
Agregaría los signos que abren, el castellano es así.

2017-04-17 16:15 UTC, xymbol commented on content/_index.es.md
> +Apuntándote en nuestro Newsletter mensual recibís en tu email toda la actividad de los distintos grupos que hacen parte de la comunidad JS en Uruguay. Una vez por mes enviamos todas las noticias con
Usaría "suscribir", creo que es más común en el ámbito de la web y sigue siendo correcto.

2017-04-18 03:42 UTC, ercpereda requested changes

2017-04-18 03:42 UTC, ercpereda commented on config.toml
> +  name = "Cómo reclamo un dominio js.uy?"
Yo dejaría *solicito*

2017-04-18 03:42 UTC, ercpereda commented on content/_about.es.md
> +En Uruguay existen muchas personas trabajando con JS al primer nivel pero a veces fallamos en comunicarle al resto del mundo lo que estamos haciendo. La mayoría de los desarrolladores fallamos en con
Después de `nivel` pondría una ,

2017-04-18 03:42 UTC, ercpereda commented on content/_about.es.md
> +Creamos `☀️.js.uy` para promover las actividades y potenciar a los integrantes de la comunidad JS en Uruguay en pos de hacer crecer la misma.
... para promover las actividades de la comunidad JS en Uruguay y potenciar a sus integrantes en pos de hacer crecer la misma.

2017-04-18 11:04 UTC, cherta commented on content/_about.es.md
> +Creemos que ayudando a la difusión a nuestras actividades vamos a tener un impacto positivo en las carreras de las personas. Ayudándolos a tener más notoriedad en la comunidad internacional y que est
Que tal algo como:

> Creemos que difundiendo mejor nuestras actividades vamos a tener un impacto positivo en las carreras de las personas. Ayudándolos a tener más visibilidad en la comunidad y que esto les permita trabajar en mejores proyectos.

Saqué lo de sueldo o ingresos y lo de mejores clientes porque pienso que decir `trabajar en mejores proyectos` deja implícito las anteriores. Un mejor proyecto puede generar mejores ingresos (a veces no siempre) pero siempre es resultado de un mejor cliente, mejor porque da más libertad, mejor porque uno aprender más, etc.

2017-04-18 11:13 UTC, cherta commented
Bueno, metí varios si no todos los comments que estaban mjy buenos. Estaría bueno darle otra vichada igual y dejarlo abierto algunos días más para que alguien más se sume.

2017-04-18 12:52 UTC, xymbol commented on content/_about.es.md
> +Creemos que ayudando a la difusión a nuestras actividades vamos a tener un impacto positivo en las carreras de las personas. Ayudándolos a tener más notoriedad en la comunidad internacional y que est
Mucho mejor, va por ahí.

2017-04-18 12:53 UTC, xymbol commented
@cherta Dale, prometo una leída de punta a punta y/o pull-request.

2017-04-24 13:16 UTC, maurocarrero commented on content/_about.es.md
> +En Uruguay existen muchas personas trabajando con JS al primer nivel pero a veces fallamos en comunicarle al resto del mundo lo que estamos haciendo. La mayoría de los desarrolladores fallamos en con
Buenas, primera colaboración de mi parte: el párrafo viene en 1ra persona, aún mencionando "algunos otros" continúa con "sabemos", entonces sería "para el desarrollo de nuestra carrera."

2017-04-24 13:38 UTC, maurocarrero commented on content/_index.es.md
> +Apuntándote en nuestro Newsletter mensual recibís en tu email toda la actividad de los distintos grupos que hacen parte de la comunidad JS en Uruguay. Una vez por mes enviamos todas las noticias con
"cada charla (videos y slides)" o "cada charla, video y slide"?
"para el mes siguiente."?

2017-04-24 13:49 UTC, maurocarrero commented on content/_about.es.md
> +Creemos que ayudando a la difusión a nuestras actividades vamos a tener un impacto positivo en las carreras de las personas. Ayudándolos a tener más notoriedad en la comunidad internacional y que est
"personas, ayudándolas..." ya que se continúa la misma idea, siendo "personas" son "las", se podría cambiar a "desarrolladores" de lo contrario.
"mayor visibilidad" en lugar de "más"?
"visibilidad en la comunidad, favoreciendo su acceso a proyectos más interesantes."?
Son sugerencias, feel free to dismiss...

2017-04-29 16:04 UTC, cherta commented
@maurocarrero creo que ahí fueron las correciones que pasaste, estaban todas re bien!

2017-04-29 18:46 UTC, merged